### ISSUE TITLE
Revisit the naming scheme and see if it needs expansion/revision based on discussions

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/design#120]
+ [ ] Naming of folders 
+ [ ] Naming of files 
+ [ ] Naming of functions 
+ [ ] Naming of classes
+ [ ] Naming of URLs
+ [ ] CLI paths

(and the storage paths)

+ [ ] Naming of different parts of our apps - e.g., "Sprout project" vs "data project" (Sprout project could be renamed to "resource"), and "instance"

**Comment by signekb** [comment]
@lwjohnst86 If we want to utilise Frictionless and Data Package standard, does it make sense to align more with their naming scheme? E.g., "data package" to  describe a dataset and "data resource" to describe a table/file?

**Comment by lwjohnst86** [comment]
I think, based on all the refactoring, designing, and changes, this is basically done. So I will close 😌
