### ISSUE TITLE
[bug]: Missing figure /images/user-data-management.svg

### ISSUE THREAD

**Issue by signekb** [seedcase-project/design#129]
### Steps to reproduce

1. Go to https://design.seedcase-project.org/software/building-block-view#user-and-data-management-layer-open-box
2. The figure "User data management" is missing. See screenshot below.
![image](https://github.com/seedcase-project/design/assets/40836345/d6c86fd6-438b-466d-bb63-36109416c027)

### Expected result

Figure should be there.

### Actual result (the bug)

It is not. 

### Severity/Priority

None

**Comment by lwjohnst86** [comment]
Long out of date, not relevant.
