### ISSUE TITLE
design/software-architecture/deployment-view: Empty 

### ISSUE THREAD

**Issue by signekb** [seedcase-project/design#13]
Maybe add a few sentences on/an outline of what this page will cover?

**Comment by martonvago** [comment]
I understand that this page will be filled in down the line, but I would find it useful to have a more focused summary here of what the other pages say about deployment plans. I'm thinking especially about the 2-container deployment scenario, i.e. one container for the data layer and for the API + UI, which is described in greater detail on the [Cross-cutting concepts page](https://design.seedcase-project.org/software/cross-cutting-concepts#storing-the-data) page. 

The docs seem to suggest a great degree of flexibility about where these two containers can be deployed, and I got a bit bogged down in thinking about hooking up a locally deployed API + UI to a remotely deployed data layer, whether there would be extra security concerns there etc. But now I understand that we mainly expect, for now at least, either a completely organisation-managed setup or a completely local setup on the user's computer.

**Comment by lwjohnst86** [comment]
@martonvago you got it. We originally thought about the 2 container solution, but it is a bit excessive for our purposes and also way more difficult to implement.

**Comment by lwjohnst86** [comment]
Many of these things have been fixed, are no longer relevant, or are addressed in other issues. Closing
