### ISSUE TITLE
design/software-architecture/runtime-view: Text/figure suggestions

### ISSUE THREAD

**Issue by signekb** [seedcase-project/design#14]
In general: 
- Mentions of "Seedcase", e.g., " [...] these data sources from their generation into Seedcase via a direct call to the API so [...]". Should it be "Seedcase Data Resource instance" or the like instead? seedcase-project/design#21 
- Mentions of "Web Portal" vs. "Web Interface" vs. "Front end". Are they the same thing? If yes, align as in seedcase-project/design#15. If no, add some context to explicitly state the difference?

**Login and authentication**
- [Figure 1](https://seedcase-project.org/design/software-architecture/runtime-view#fig-login-sequence): 
    - This is the first page where figure numbering is used. seedcase-project/seedcase-project#167 
    - https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/runtime-view.qmd#L14
 
**Expected type of input data**
- Should it be added that we also expect images as mentioned in [Building block view](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/building-block-view.qmd#L323)?
- Mention of a "batch-input Web Portal". Will there be separate "portals" for routine or continuous data and batch collection? If yes, maybe be a bit more explicit about that, also in the Building Block view post?
    - https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/runtime-view.qmd#L114-L116

- Mention of ["authorized users"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/runtime-view.qmd#L127) -> who are these authorised users? A subgroup of the four user groups described under System context and scope?  

**Manual data entry: Done in one *session***
- Not sure what is mean by "session" here. Maybe add a sentence on that so it's explicit? :-)
- "The *approved user* will open the login screen in the Web Portal." - who is the approved user? Approved by who? Add some more context here - and maybe add this detail to the user descriptions under System context and scope?
- It's only clear from the figure that the user is manually entering *one* row. Can the user not manually enter multiple rows in one go? 
- Figure text: Add meaning of the abbreviation "UI" used in the figure?

**Applying for a new data project**
- Include a description of what happens if a project is rejected or needs modifications? How/where will the admin and data requester's communication go if there is a need to go "negotiate" e.g., variables or timeframes included in the data project?

**Comment by lwjohnst86** [comment]
Many of these things have been fixed, are no longer relevant, or are addressed in other issues. Closing
