### ISSUE TITLE
design/software-architecture/solution-strategy: Text suggestions

### ISSUE THREAD

**Issue by signekb** [seedcase-project/design#16]
- The list "In relation to our Quality goals": 
    - https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/solution-strategy.qmd#L42-L43 
        - Do we know which established protocols that will be used yet? If yes, the could be added here. Potentially with links. 
    - https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/solution-strategy.qmd#L47-L48 
        - Second mention of Test-Driven Dev (with link to wikipedia). Should we add a post on this instead describing how we practice this? - Or add Test-Driven Dev to the post on Documentation Driven Development?

**Comment by signekb** [comment]
Will wait with this until #92 and #100 has been merged.

**Comment by lwjohnst86** [comment]
Many of these things have been fixed, are no longer relevant, or are addressed in other issues. Closing
