### ISSUE TITLE
design/software-architecture/System context and scope: Text/figure clarification suggestions

### ISSUE THREAD

**Issue by signekb** [seedcase-project/design#17]
- Could the title "System context and scope" be a bit more clear on what this page is on? Something like "Types of Data Resource Connections" or the like seems mole relevant to the text, which mainly describes how the four user types "access" a data resource (+ data might be extracted to a potential external system). Alternatively, we could add some introductory sentences clarifying what is meant by "System context and scope", and how it relates to the text? 

- Figure: 
    - Add to the arrow text to External secure server, "Data extract for approved data projects", that it is only necessary when the user who is requesting access is an external partner to those who control the Data Resource (as described in the [text](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/context.qmd#L52-L56))? 
        - If yes, it would be relevant on other figures as well. E.g., Figure ["C4 Container diagram showing the major internal parts of Seedcase"](https://seedcase-project.org/design/software-architecture/building-block-view#level1) on the Building Block View page.

- User 1, point 2: Just a general question :-) 
    - How is it going to work with plugins in Seedcase? Are external contributors going to be able to add their own plugins which will transform the data into a specific format? Maybe we could write a bit more about that here or somewhere else?   
    - https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/context.qmd#L22-L25
   
- User 3: 
    - What is the difference between an administrator and a data controller? Maybe clarify here? :-)  
    - https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/context.qmd#L34-L35 
 
The post *Cross-cutting concepts* actually, indirectly offers names for each user type in the [table](https://seedcase-project.org/design/software-architecture/cross-cutting-concepts#permissions) under *User Permissions*: 
- Admin, Data request, Data entry, Third party. Maybe this naming could be aligned across the documentation?

**Comment by lwjohnst86** [comment]
Closed by the other linked PRs
