### ISSUE TITLE
design/software-architecture/constraints: Text clarification suggestions

### ISSUE THREAD

**Issue by signekb** [seedcase-project/design#18]
- Maybe include a sentence or two before each table on this page. As a reader, I am not entirely sure what is meant by e.g., "Conventions" 

**Introduction/first section**
- https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/constraints.qmd#L12-L16
    - Mentions it is **summarizing** from Guiding Principles but then adds information not mentioned explicitly in Guiding Principles (e.g., "Run on Windows, MacOS, and Linux" under "Technical constraints". Should this be mentioned in the Guiding Principles? Alternatively, the we could change the wording here to something like *elaborating* instead? 

**Technical constraints**
- [L27](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/constraints.qmd#L27): "Where data are stored vs analyzed will likely be different, see subsection below" --> As a reader, I'm unsure of which subsection that's referred to here. Maybe explicitly state which subsection and/or link to it? 

**Political/legal constraints** 
- [L47](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/constraints.qmd#L47): "Need endorsement from legal and IT" - there might be missing a word here? legal *what*?

**Conventions** 
- "Follow standard styling (e.g., PIP3)":
    -  Which other standard stylings? 
    - "Coding style is vital to readability, so we follow best practice" - best practice according to who/which principles? :-)
-  https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/constraints.qmd#L57 
    - First mention of Test-Driven development. Do we use that? If yes, shouldn't it be described, potentially in a decision post or a post like the Documentation First Culture post?

**Comment by lwjohnst86** [comment]
Many of these things have been fixed, are no longer relevant, or are addressed in other issues. Closing
