### ISSUE TITLE
design/software-architecture/introduction: Text clarification suggestions

### ISSUE THREAD

**Issue by signekb** [seedcase-project/design#19]
This became quite a long issue - but this is also a long post. Let me know, if these kinds of issues could be optimised in some way :-) 

**Introduction**
- Can we be clearer of what we mean by "Seedcase" vs "the framework" vs "Seedcase project" vs "Seedcase software"? Relevant for the entire page/all mentions of Seedcase. Relates to seedcase-project/design#21 
    - [L8-L15](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L8-L15 ): "_Seedcase_ was born [...]. The connected Design documents describe the architecture of the _Seedcase software_ as well as the underlying data architecture that _Seedcase_ implements as a framework. Our specific goals for the _Seedcase project_ are: [...]"
 
- As a reader, I am unsure of how the aims impact decisions? Could we include a sentence clarifying this - or include a link to where you can find info on this? 
- https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L28-L30

**Definition of terms** 
- List: https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L32-L35
    - Maybe add a sentence before the bullet list to make it clearer what the list covers definitions of? 

**Requirements Overview**
- Add an introductory sentence of what to expect in this section (since there are quite a few subheadings in this section)? 

**Main functionality** 
- Add introductory sentence to make it clearer what this list/section contains? It is not explicitly clear to me what "Main functionality" entails
- Unfinished sentence under "Provide a data access submission process:": https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L173-L178
- A general question which is not explicitly stated here: Will non-approved projects be shown along side approved projects? In theory, that could help to avoid similar requests being made in the future? 

**Quality Goals**
- Add some sentences/context to this section? Currently, it's only a (very nice) table :-) 

This post ends quite abruptly. It might be nice with a less abrupt ending that summarises or concludes on this rather long post? Alternatively, we could add an overview of what's in the remaining pages?

**Comment by lwjohnst86** [comment]
Many of these things have been fixed, are no longer relevant, or are addressed in other issues. Closing
