### ISSUE TITLE
Generally: Mentions of "Seedcase", "Seedcase Project",  "Seedcase the software product", "Seedcase Data Resource", etc.

### ISSUE THREAD

**Issue by signekb** [seedcase-project/design#21]
Apologies for this becoming such a long issue :-) 

Throughout the texts, there are (naturally) mentions of Seedcase. However, as a reader, it can be quite confusing to understand what is meant when there's referred to different parts of "Seedcase" .

I think that being more precise with what we call the different parts of Seedcase (the entire project), this might really help clarify what is meant throughout almost the entire documentation :-)

It seems that there are (at least) three parts of Seedcase that are described in various way across the documentations: 

- Seedcase Project (the entire thing - including software and documentation of software, culture, collaboration, "how's" and "why's") 
- Seedcase Product (the software product)
- Seedcase Data Resource (a specific instance created with the software?)

For me, it gets particularly confusing, with mentions of "Seedcase" or "the Seedcase", because it seems which parts that is differs across the texts. For example: 
- Community/index: "Seedcase" referring to the Seedcase Software (I think?)
    - https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/community/index.qmd#L9-L10

- Design/index: Many mentions of "Seedcase" - but I think it refers to the "Seedcase Software"? 
    - https://github.com/seedcase-project/seedcase-project/blob/56e3536e6b1bb543e82beea91d95f43fd53433ea/design/index.md?plain=1#L30-L34
    - https://github.com/seedcase-project/seedcase-project/blob/56e3536e6b1bb543e82beea91d95f43fd53433ea/design/index.md?plain=1#L37-L39
    - https://github.com/seedcase-project/seedcase-project/blob/56e3536e6b1bb543e82beea91d95f43fd53433ea/design/index.md?plain=1#L42-L47

- Design/software-architecture/Building block view: "the seedcase" referring to (what I believe to be) a "seedcase data resource instance"?
    - https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/building-block-view.qmd#L76-L76
- Design/software-architecture/introduction: 
   - https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L12-L15 

On top of this, I'm a bit confused about the "data components" vs "software" of seedcase mentioned in design/software-architecture/introduction:
https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L64-L65

as well as the "framework": Is that the entire "Seedcase Project"? 
- https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L12-L15
https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L19-L25

Idea: We could implement when users hover their mouse over the different parts, their definitions would come up?

------------------------------------------

In the following, I have found some specific examples of different words used for the same thing: 

**The "Seedcase Software Product":**
- Community/blocks: ["Seedcase software "Product" itself"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/community/blocks.qmd#L16-L17) vs. ["Seedcase the software"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/community/blocks.qmd#L7-L9) vs. ["Seedcase Product"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/community/blocks.qmd#L18) vs. ["The Product"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/community/blocks.qmd#L26)

- Design/software-architecture/introduction: First mentions it as ["Seedcase software"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L13), then defines it as ["Seedcase Product"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L34-L35), and afterwards refer to it as the ["Seedcase software"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L45) again

**"Seedcase Data Resource":**
- design/software-architecture/context (figure): ["Seedcase System for Data Resource"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/images/context.puml#L12)
- design/software-architecture/introduction: ["One Seedcase "instance" per Data Resource"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/introduction.qmd#L158-L160)
- design/software-architecture/runtime-view: ["Seedcase-managed Data Resources"](https://github.com/seedcase-project/seedcase-project/blob/d6086fe2ca077597dc7cf00db9d863055f04139e/design/software-architecture/runtime-view.qmd#L12-L13)

**Comment by martonvago** [comment]
I've been looking into this and ran into some questions:
* "the Seedcase software product" vs "Seedcase software products": when talking in general, do we always prefer the plural (as there will be multiple more or less independent bits)? That would work with "Seedcase software" being plural as well, at least conceptually. 
* It feels like a big part of the docs was written with a single, or at least a core/main, product in mind. Do we have a preferred way of referring to this core/main product? It's tempting to say that it's Sprout, but I don't think that's entirely correct, because judging by the [roadmap](https://community.seedcase-project.org/roadmap), Sprout is more like the implementation of one user journey of the core product. 

I'm mainly asking because it wouldn't make sense to reword all of the docs to make them talk about a plurality of products, but it is confusing that some docs imply that there is a single product, while others imply that there are multiple.

(@lwjohnst86 or @seedcase-project/developers :slightly_smiling_face: )
