### ISSUE TITLE
Architecture: Deployment View

### ISSUE THREAD

**Issue by lwjohnst86** [seedcase-project/design#26]
[Deployment view](https://docs.arc42.org/section-7/) describes the technical and hardware infrastructure that the project will (assumed to be) run on, as well as what the "tech stack" might be.

- [ ] Insert Deployment diagram here: seedcase-project/design#36 
- [ ] seedcase-project/seedcase-sprout#5

**Comment by K-Beicher** [comment]
Closed after discussion as it is outdated.
